// 전국 대학교 목록 (4년제 + 주요 전문대 포함, 대표 목록)
export const UNIVERSITIES: string[] = [
  // 서울
  "서울대학교",
  "연세대학교",
  "고려대학교",
  "서강대학교",
  "성균관대학교",
  "한양대학교",
  "중앙대학교",
  "경희대학교",
  "한국외국어대학교",
  "서울시립대학교",
  "건국대학교",
  "동국대학교",
  "홍익대학교",
  "숙명여자대학교",
  "이화여자대학교",
  "성신여자대학교",
  "덕성여자대학교",
  "동덕여자대학교",
  "서울여자대학교",
  "광운대학교",
  "국민대학교",
  "숭실대학교",
  "세종대학교",
  "단국대학교",
  "명지대학교",
  "상명대학교",
  "삼육대학교",
  "서경대학교",
  "성공회대학교",
  "한성대학교",
  "추계예술대학교",
  "총신대학교",
  "서울과학기술대학교",
  "한국체육대학교",
  // 인천/경기
  "인천대학교",
  "인하대학교",
  "가천대학교",
  "아주대학교",
  "경기대학교",
  "수원대학교",
  "한신대학교",
  "협성대학교",
  "용인대학교",
  "강남대학교",
  "대진대학교",
  "안양대학교",
  "한경국립대학교",
  "한국항공대학교",
  "한국산업기술대학교",
  "차의과학대학교",
  "신한대학교",
  "을지대학교",
  "platform-경동대학교",
  // 강원
  "강원대학교",
  "강릉원주대학교",
  "한림대학교",
  "연세대학교(미래)",
  "가톨릭관동대학교",
  "상지대학교",
  "한라대학교",
  // 충청
  "충남대학교",
  "충북대학교",
  "한밭대학교",
  "공주대학교",
  "순천향대학교",
  "단국대학교(천안)",
  "건양대학교",
  "배재대학교",
  "대전대학교",
  "목원대학교",
  "한남대학교",
  "우송대학교",
  "청주대학교",
  "서원대학교",
  "한국교통대학교",
  "세명대학교",
  "중부대학교",
  "선문대학교",
  "호서대학교",
  "남서울대학교",
  "백석대학교",
  "KAIST(한국과학기술원)",
  "UST(과학기술연합대학원대학교)",
  // 대구/경북
  "경북대학교",
  "영남대학교",
  "계명대학교",
  "대구대학교",
  "대구가톨릭대학교",
  "안동대학교",
  "금오공과대학교",
  "경운대학교",
  "대구한의대학교",
  "위덕대학교",
  "한동대학교",
  "동국대학교(경주)",
  "DGIST(대구경북과학기술원)",
  "포항공과대학교(POSTECH)",
  // 부산/울산/경남
  "부산대학교",
  "부경대학교",
  "동아대학교",
  "경성대학교",
  "동의대학교",
  "동서대학교",
  "신라대학교",
  "고신대학교",
  "부산외국어대학교",
  "한국해양대학교",
  "울산대학교",
  "UNIST(울산과학기술원)",
  "경상국립대학교",
  "창원대학교",
  "인제대학교",
  "경남대학교",
  "영산대학교",
  // 광주/전라
  "전남대학교",
  "전북대학교",
  "조선대학교",
  "광주대학교",
  "호남대학교",
  "광주여자대학교",
  "남부대학교",
  "송원대학교",
  "GIST(광주과학기술원)",
  "원광대학교",
  "군산대학교",
  "전주대학교",
  "우석대학교",
  "예수대학교",
  "목포대학교",
  "순천대학교",
  "동신대학교",
  "초당대학교",
  "세한대학교",
  // 제주
  "제주대학교",
  "제주국제대학교",
]
  .filter((u) => !u.startsWith("platform-"))
  .sort((a, b) => a.localeCompare(b, "ko"))

// 대학교별 학교 이메일 도메인 (대표 도메인 기준, 일부는 복수 허용)
// key 는 UNIVERSITIES 목록의 이름과 정확히 일치해야 합니다.
export const SCHOOL_EMAIL_DOMAINS: Record<string, string[]> = {
  // 서울
  서울대학교: ["snu.ac.kr"],
  연세대학교: ["yonsei.ac.kr"],
  "연세대학교(미래)": ["yonsei.ac.kr"],
  고려대학교: ["korea.ac.kr"],
  서강대학교: ["sogang.ac.kr"],
  성균관대학교: ["skku.edu", "g.skku.edu"],
  한양대학교: ["hanyang.ac.kr"],
  중앙대학교: ["cau.ac.kr"],
  경희대학교: ["khu.ac.kr"],
  한국외국어대학교: ["hufs.ac.kr"],
  서울시립대학교: ["uos.ac.kr"],
  건국대학교: ["konkuk.ac.kr"],
  동국대학교: ["dongguk.edu", "dgu.ac.kr"],
  홍익대학교: ["hongik.ac.kr", "g.hongik.ac.kr", "mail.hongik.ac.kr"],
  숙명여자대학교: ["sookmyung.ac.kr", "sm.ac.kr"],
  이화여자대학교: ["ewha.ac.kr", "ewhain.net"],
  성신여자대학교: ["sungshin.ac.kr"],
  덕성여자대학교: ["duksung.ac.kr"],
  동덕여자대학교: ["dongduk.ac.kr"],
  서울여자대학교: ["swu.ac.kr"],
  광운대학교: ["kw.ac.kr"],
  국민대학교: ["kookmin.ac.kr"],
  숭실대학교: ["soongsil.ac.kr", "ssu.ac.kr"],
  세종대학교: ["sejong.ac.kr"],
  단국대학교: ["dankook.ac.kr"],
  "단국대학교(천안)": ["dankook.ac.kr"],
  명지대학교: ["mju.ac.kr"],
  상명대학교: ["sangmyung.kr", "smu.ac.kr"],
  삼육대학교: ["syu.ac.kr"],
  서경대학교: ["skuniv.ac.kr"],
  성공회대학교: ["skhu.ac.kr"],
  한성대학교: ["hansung.ac.kr"],
  추계예술대학교: ["chugye.ac.kr"],
  총신대학교: ["chongshin.ac.kr"],
  서울과학기술대학교: ["seoultech.ac.kr"],
  한국체육대학교: ["knsu.ac.kr"],
  // 인천/경기
  인천대학교: ["inu.ac.kr"],
  인하대학교: ["inha.ac.kr", "inha.edu"],
  가천대학교: ["gachon.ac.kr"],
  아주대학교: ["ajou.ac.kr"],
  경기대학교: ["kyonggi.ac.kr", "kgu.ac.kr"],
  수원대학교: ["suwon.ac.kr"],
  한신대학교: ["hs.ac.kr"],
  협성대학교: ["uhs.ac.kr"],
  용인대학교: ["yongin.ac.kr"],
  강남대학교: ["kangnam.ac.kr"],
  대진대학교: ["daejin.ac.kr"],
  안양대학교: ["anyang.ac.kr"],
  한경국립대학교: ["hknu.ac.kr"],
  한국항공대학교: ["kau.ac.kr"],
  한국산업기술대학교: ["kpu.ac.kr", "tukorea.ac.kr"],
  차의과학대학교: ["cha.ac.kr"],
  신한대학교: ["shinhan.ac.kr"],
  을지대학교: ["eulji.ac.kr"],
  // 강원
  강원대학교: ["kangwon.ac.kr"],
  강릉원주대학교: ["gwnu.ac.kr"],
  한림대학교: ["hallym.ac.kr"],
  가톨릭관동대학교: ["cku.ac.kr"],
  상지대학교: ["sangji.ac.kr"],
  한라대학교: ["halla.ac.kr"],
  // 충청
  충남대학교: ["cnu.ac.kr"],
  충북대학교: ["chungbuk.ac.kr", "cbnu.ac.kr"],
  한밭대학교: ["hanbat.ac.kr"],
  공주대학교: ["kongju.ac.kr", "smail.kongju.ac.kr"],
  순천향대학교: ["sch.ac.kr"],
  건양대학교: ["konyang.ac.kr"],
  배재대학교: ["pcu.ac.kr"],
  대전대학교: ["dju.ac.kr", "edu.dju.ac.kr"],
  목원대학교: ["mokwon.ac.kr"],
  한남대학교: ["hnu.kr"],
  우송대학교: ["wsu.ac.kr"],
  청주대학교: ["cju.ac.kr"],
  서원대학교: ["seowon.ac.kr"],
  한국교통대학교: ["ut.ac.kr"],
  세명대학교: ["semyung.ac.kr"],
  중부대학교: ["joongbu.ac.kr"],
  선문대학교: ["sunmoon.ac.kr"],
  호서대학교: ["hoseo.edu"],
  남서울대학교: ["nsu.ac.kr"],
  백석대학교: ["bu.ac.kr"],
  "KAIST(한국과학기술원)": ["kaist.ac.kr"],
  "UST(과학기술연합대학원대학교)": ["ust.ac.kr"],
  // 대구/경북
  경북대학교: ["knu.ac.kr"],
  영남대학교: ["yu.ac.kr", "ynu.ac.kr"],
  계명대학교: ["kmu.kr", "gw.kmu.ac.kr"],
  대구대학교: ["daegu.ac.kr"],
  대구가톨릭대학교: ["cu.ac.kr"],
  안동대학교: ["anu.ac.kr"],
  금오공과대학교: ["kumoh.ac.kr"],
  경운대학교: ["ikw.ac.kr"],
  대구한의대학교: ["dhu.ac.kr"],
  위덕대학교: ["uu.ac.kr"],
  한동대학교: ["handong.edu", "handong.ac.kr"],
  "동국대학교(경주)": ["dongguk.ac.kr"],
  "DGIST(대구경북과학기술원)": ["dgist.ac.kr"],
  "포항공과대학교(POSTECH)": ["postech.ac.kr"],
  // 부산/울산/경남
  부산대학교: ["pusan.ac.kr"],
  부경대학교: ["pukyong.ac.kr"],
  동아대학교: ["donga.ac.kr"],
  경성대학교: ["ks.ac.kr"],
  동의대학교: ["deu.ac.kr"],
  동서대학교: ["dongseo.ac.kr", "gdsu.dongseo.ac.kr"],
  신라대학교: ["silla.ac.kr"],
  고신대학교: ["kosin.ac.kr"],
  부산외국어대학교: ["bufs.ac.kr"],
  한국해양대학교: ["kmou.ac.kr"],
  울산대학교: ["ulsan.ac.kr", "mail.ulsan.ac.kr"],
  "UNIST(울산과학기술원)": ["unist.ac.kr"],
  경상국립대학교: ["gnu.ac.kr"],
  창원대학교: ["changwon.ac.kr"],
  인제대학교: ["inje.ac.kr"],
  경남대학교: ["kyungnam.ac.kr"],
  영산대학교: ["ysu.ac.kr"],
  // 광주/전라
  전남대학교: ["jnu.ac.kr", "chonnam.ac.kr"],
  전북대학교: ["jbnu.ac.kr"],
  조선대학교: ["chosun.ac.kr", "chosun.kr"],
  광주대학교: ["gwangju.ac.kr"],
  호남대학교: ["honam.ac.kr"],
  광주여자대학교: ["kwu.ac.kr"],
  남부대학교: ["nambu.ac.kr"],
  송원대학교: ["songwon.ac.kr"],
  "GIST(광주과학기술원)": ["gist.ac.kr", "gm.gist.ac.kr"],
  원광대학교: ["wku.ac.kr", "wonkwang.ac.kr"],
  군산대학교: ["kunsan.ac.kr"],
  전주대학교: ["jj.ac.kr"],
  우석대학교: ["woosuk.ac.kr"],
  예수대학교: ["jesus.ac.kr"],
  목포대학교: ["mokpo.ac.kr"],
  순천대학교: ["scnu.ac.kr", "sunchon.ac.kr"],
  동신대학교: ["dsu.ac.kr"],
  초당대학교: ["cdu.ac.kr"],
  세한대학교: ["sehan.ac.kr"],
  // 제주
  제주대학교: ["jejunu.ac.kr"],
  제주국제대학교: ["jju.ac.kr"],
}

// 학교 이메일 도메인 검증에 사용할 헬퍼.
// 등록된 도메인이 있으면 해당 도메인만 허용하고, 없으면 학술 도메인(.ac.kr/.edu)을 폭넓게 허용합니다.
export function getSchoolEmailDomains(school: string | null | undefined): string[] {
  if (!school) return []
  return SCHOOL_EMAIL_DOMAINS[school] ?? []
}

export function getEmailDomain(email: string): string {
  const at = email.lastIndexOf("@")
  if (at < 0) return ""
  return email.slice(at + 1).trim().toLowerCase()
}

export function isSchoolEmail(email: string, school: string | null | undefined): boolean {
  const domain = getEmailDomain(email)
  if (!domain) return false
  const allowed = getSchoolEmailDomains(school)
  if (allowed.length > 0) {
    return allowed.some((d) => domain === d.toLowerCase())
  }
  // 등록되지 않은 학교는 일반 학술 도메인을 허용 (예: ac.kr, edu)
  return domain.endsWith(".ac.kr") || domain.endsWith(".edu") || domain.endsWith(".edu.kr")
}

// 분류 1차: 전체 / 전공 / 교양 / 기타
export type Category = "전체" | "전공" | "교양" | "기타"
export const CATEGORIES: Category[] = ["전체", "전공", "교양", "기타"]

// 교양 하위 분류
export const LIBERAL_GROUPS: string[] = [
  "인성교양",
  "기초교양",
  "핵심교양",
  "일반교양",
  "필수교양",
  "선택교양",
  "외국어교양",
  "SW/AI교양",
]

// 학년
export const GRADES: string[] = ["1학년", "2학년", "3학년", "4학년", "기타"]

// 도서 상태
export const CONDITIONS: string[] = ["새책", "상", "중", "하"]

// 계열별 학과 목록 — 전국 대학에서 공통적으로 개설되는 학과를 폭넓게 정리한 데이터
export const DEPARTMENTS_BY_COLLEGE: Record<string, string[]> = {
  인문계열: [
    "국어국문학과",
    "영어영문학과",
    "중어중문학과",
    "일어일문학과",
    "독어독문학과",
    "불어불문학과",
    "노어노문학과",
    "서어서문학과",
    "사학과",
    "철학과",
    "문헌정보학과",
    "고고학과",
    "종교학과",
    "언어학과",
    "문예창작학과",
    "한문학과",
  ],
  사회과학계열: [
    "정치외교학과",
    "행정학과",
    "사회학과",
    "심리학과",
    "사회복지학과",
    "언론정보학과",
    "신문방송학과",
    "미디어커뮤니케이션학과",
    "지리학과",
    "국제학부",
    "정책학과",
    "경찰행정학과",
    "부동산학과",
    "문화인류학과",
  ],
  경상계열: [
    "경제학과",
    "경영학과",
    "회계학과",
    "무역학과",
    "국제통상학과",
    "금융학과",
    "세무학과",
    "물류학과",
    "e비즈니스학과",
    "관광경영학과",
    "호텔경영학과",
  ],
  법학계열: ["법학과", "법학부", "공법학과", "사법학과", "지식재산학과"],
  사범계열: [
    "교육학과",
    "국어교육과",
    "영어교육과",
    "수학교육과",
    "과학교육과",
    "사회교육과",
    "역사교육과",
    "지리교육과",
    "윤리교육과",
    "체육교육과",
    "유아교육과",
    "초등교육과",
    "특수교육과",
    "교육공학과",
  ],
  자연과학계열: [
    "수학과",
    "물리학과",
    "화학과",
    "생명과학과",
    "생물학과",
    "통계학과",
    "지구환경과학과",
    "천문우주학과",
    "대기과학과",
    "해양학과",
    "식품영양학과",
    "의류학과",
    "주거환경학과",
  ],
  공학계열: [
    "기계공학과",
    "전기공학과",
    "전자공학과",
    "전기전자공학부",
    "컴퓨터공학과",
    "소프트웨어학과",
    "인공지능학과",
    "정보통신공학과",
    "산업공학과",
    "화학공학과",
    "신소재공학과",
    "재료공학과",
    "토목공학과",
    "건축공학과",
    "건축학과",
    "환경공학과",
    "에너지공학과",
    "항공우주공학과",
    "조선해양공학과",
    "원자력공학과",
    "도시공학과",
    "데이터사이언스학과",
    "반도체공학과",
    "생명공학과",
  ],
  의약계열: [
    "의예과",
    "의학과",
    "치의학과",
    "한의학과",
    "약학과",
    "간호학과",
    "수의예과",
    "물리치료학���",
    "작업치료학과",
    "방사선학과",
    "임상병리학과",
    "치위생학과",
    "응급구조학과",
    "보건행정학과",
    "재활학과",
  ],
  예체능계열: [
    "음악학과",
    "성악과",
    "기악과",
    "작곡과",
    "미술학과",
    "회화과",
    "조소과",
    "디자인학과",
    "시각디자인학과",
    "산업디자인학과",
    "패션디자인학과",
    "공예학과",
    "사진학과",
    "연극영화학과",
    "무용학과",
    "체육학과",
    "스포츠과학과",
    "태권도학과",
    "실용음악과",
    "만화애니메이션학과",
  ],
  농생명계열: [
    "농업생명과학과",
    "원예학과",
    "산림학과",
    "조경학과",
    "축산학과",
    "동물자원학과",
    "식물자원학과",
    "환경원예학과",
    "바이오시스템공학과",
  ],
}

export const COLLEGE_ORDER = Object.keys(DEPARTMENTS_BY_COLLEGE)

// 모든 학과 평탄화
export const ALL_DEPARTMENTS: string[] = COLLEGE_ORDER.flatMap(
  (c) => DEPARTMENTS_BY_COLLEGE[c],
)
